FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

RUN npm run build

FROM node:20

WORKDIR /app

COPY --from=builder /app .

EXPOSE 5000

CMD ["npm", "start"]
