version: '3.8'

services:
  backend:
    build:
      context: .  
      dockerfile: Dockerfile.dev   
    ports:
      - "5000:5000"  
    volumes:
      - ./:/app  
    environment:
      NODE_ENV: development  
