//LABELS ENPOINTS requires AUTH
###
GET http://localhost:5000/labels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc3NzE5MzEsImV4cCI6MTcwNzc3MjgzMX0.nr2keMbfPofIDcT32AuKcEmDLYoCfdD8Q3hFb4_tC1s

###
POST http://localhost:5000/labels/create-label
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc3NzE0MTUsImV4cCI6MTcwNzc3MjMxNX0.Pw664ARwqI82ILyCnA0C7nClREPv6f24VoJw3kVYWTU

{
  "name": "NázovVášhoŠtítku112",
  "createdBy": "65c8e5526d6a7f9d48787034"
}

###
DELETE http://localhost:5000/labels/delete-label/65ca35cc578c2c3ccc078dfa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc3NzEyNjIsImV4cCI6MTcwNzc3MjE2Mn0.QzdQzawvFNTmWPtw8wvOw84o761I-YU0_s8scneJqp8

###
PUT http://localhost:5000/labels/edit-label/65ca35d2578c2c3ccc078e01
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc3NzE2MDksImV4cCI6MTcwNzc3MjUwOX0.Q85-n4VKfHKonezzn96eyvJyErffT5GvMkQCKKvyJU8

{
  "name": "NázovŠtítk"
}

###
GET http://localhost:5000/labels/get-label/65ca35d2578c2c3ccc078e01
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc3NzE5MzEsImV4cCI6MTcwNzc3MjgzMX0.nr2keMbfPofIDcT32AuKcEmDLYoCfdD8Q3hFb4_tC1s


// USERS ENPOINTS requires AUTH
####
GET http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc3NDM5MDMsImV4cCI6MTcwNzc0NDgwM30.reHcajICwEke42p1KFc5qPShwZ9oHZ6QARFj2t15KcU


###
DELETE http://localhost:5000/users/65c8e5526d6a7f9d48787034
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc3Njk4NTcsImV4cCI6MTcwNzc3MDc1N30.2bgVipTtDxHXt7AKpkKwXSAIWfD1Z16Wz4OWQzDXVJY

###
PUT http://localhost:5000/users/edit-user/65c8e5526d6a7f9d48787034
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc2ODQwMDMsImV4cCI6MTcwNzY4NDkwM30.YlNPdB__YHOPihz13ybSMWHR156ip6Uymr9ay8igRqU

{
  "firstName": "Romeo",
  "lastName": "Dzem",
  "email": "r.jamrisko@gmail.com"
}


###
POST  http://localhost:5000/users/assign-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc2ODQwMDMsImV4cCI6MTcwNzY4NDkwM30.YlNPdB__YHOPihz13ybSMWHR156ip6Uymr9ay8igRqU


{
  "userId": "65c8e5526d6a7f9d48787034",
  "role": "admin"
}


###
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "firstName":"Roman",
  "lastName": "Jamriško",
  "email": "r.jamriško@gmail.com",
  "password": "123456"
}
###
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "email": "r.jamrisko@gmail.com",
  "password": "123456"
}
### 
POST http://localhost:5000/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWMxZjkwNjk1ZDc4YmVkNGJiZjE4NTciLCJpYXQiOjE3MDcyMTEyMTQsImV4cCI6MTcwNzIxMjExNH0.4TGTmZjjjhhBt2M-7O2HpKZW52SZZ8pJc5oX4dY89Yo

###
GET http://localhost:5000/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWMxZjkwNjk1ZDc4YmVkNGJiZjE4NTciLCJpYXQiOjE3MDcyMTEyMTQsImV4cCI6MTcwNzIxMjExNH0.4TGTmZjjjhhBt2M-7O2HpKZW52SZZ8pJc5oX4dY89Yo

###
POST http://localhost:5000/users/reset-password-request
Content-Type: application/json

{
  "email": "r.jamrisko@gmail.com"
}

###
POST http://localhost:5000/users/reset-password/65c1f90695d78bed4bbf1857/79a4a9e87c935cd1eb0609faaf21763997ebbb65e58fbf2582c281fb9c2f0454
Content-Type: application/json

{
  "password": "12345644"
}

