GET http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc2ODQwMDMsImV4cCI6MTcwNzY4NDkwM30.YlNPdB__YHOPihz13ybSMWHR156ip6Uymr9ay8igRqU


###
DELETE http://localhost:5000/users/65c8e475f68a59d6276fa5ba
Content-Type: application/json

###
PUT http://localhost:5000/users/edit-user/65c8e5526d6a7f9d48787034
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc2ODQwMDMsImV4cCI6MTcwNzY4NDkwM30.YlNPdB__YHOPihz13ybSMWHR156ip6Uymr9ay8igRqU

{
  "firstName": "Romeo",
  "lastName": "Dzem",
  "email": "r.jamrisko@gmail.com"
}


###
POST  http://localhost:5000/users/assign-role
Content-Type: application/json

{
  "userId": "65c8e5526d6a7f9d48787034",
  "role": "admin"
}


###
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "firstName":"Roman",
  "lastName": "Jamriško",
  "email": "r.jamriško@gmail.com",
  "password": "123456"
}
###
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "email": "r.jamrisko@gmail.com",
  "password": "123456"
}
### 
POST http://localhost:5000/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWMxZjkwNjk1ZDc4YmVkNGJiZjE4NTciLCJpYXQiOjE3MDcyMTEyMTQsImV4cCI6MTcwNzIxMjExNH0.4TGTmZjjjhhBt2M-7O2HpKZW52SZZ8pJc5oX4dY89Yo

###
GET http://localhost:5000/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWMxZjkwNjk1ZDc4YmVkNGJiZjE4NTciLCJpYXQiOjE3MDcyMTEyMTQsImV4cCI6MTcwNzIxMjExNH0.4TGTmZjjjhhBt2M-7O2HpKZW52SZZ8pJc5oX4dY89Yo

###
POST http://localhost:5000/users/reset-password-request
Content-Type: application/json

{
  "email": "r.jamrisko@gmail.com"
}

###
POST http://localhost:5000/users/reset-password/65c1f90695d78bed4bbf1857/79a4a9e87c935cd1eb0609faaf21763997ebbb65e58fbf2582c281fb9c2f0454
Content-Type: application/json

{
  "password": "12345644"
}

