//LABELS ENPOINTS requires AUTH
###
GET https://localhost:5000/labels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDgwOTkyNTcsImV4cCI6MTcwODEwMDE1N30.Lpvdu0WXOnwXKvD20SVdg2SsZL-oJLKtms-JPSUWOJE

###
POST https://localhost:5000/labels/create-label
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDgwOTkyNTcsImV4cCI6MTcwODEwMDE1N30.Lpvdu0WXOnwXKvD20SVdg2SsZL-oJLKtms-JPSUWOJE

{
  "name": "label2",
  "createdBy": "65c8e5526d6a7f9d48787034"
}

###
DELETE https://localhost:5000/labels/delete-label/65cf8763c96f7849b4c401d1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDgwOTkyNTcsImV4cCI6MTcwODEwMDE1N30.Lpvdu0WXOnwXKvD20SVdg2SsZL-oJLKtms-JPSUWOJE

###
PUT https://localhost:5000/labels/edit-label/65ca35d2578c2c3ccc078e01
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc3NzE2MDksImV4cCI6MTcwNzc3MjUwOX0.Q85-n4VKfHKonezzn96eyvJyErffT5GvMkQCKKvyJU8

{
  "name": "NázovŠtítk"
}

###
GET https://localhost:5000/labels/get-label/65ca35d2578c2c3ccc078e01
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc3NzE5MzEsImV4cCI6MTcwNzc3MjgzMX0.nr2keMbfPofIDcT32AuKcEmDLYoCfdD8Q3hFb4_tC1s


 

