name: CI

on:
  push:
    branches:
      - main  # alebo iná vetva, ktorú chceš sledovať

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t romanca/trello-clone:latest .
          # Tu nahrad 'romanca' svojím Docker Hub užívateľským menom

      - name: Push Docker image
        run: |
          docker push romanca/trello-clone:latest
