###
GET https://localhost:5000/todos/65cf8768c96f7849b4c401d9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDgwOTkyNTcsImV4cCI6MTcwODEwMDE1N30.Lpvdu0WXOnwXKvD20SVdg2SsZL-oJLKtms-JPSUWOJE

###
POST https://localhost:5000/todos/create-todo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDgwOTkyNTcsImV4cCI6MTcwODEwMDE1N30.Lpvdu0WXOnwXKvD20SVdg2SsZL-oJLKtms-JPSUWOJE

{
  "title": "Todo4",
  "createdBy": "65c8e5526d6a7f9d48787034",
  "labelId": "65cf8768c96f7849b4c401d9"
}

###
DELETE https://localhost:5000/todos/delete-todo/65cd2a86ff14fe595dfa4558
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDgwOTcwOTYsImV4cCI6MTcwODA5Nzk5Nn0.4f1hOW_GtY7nsIozCmCLSZ6myeT8UW827B2YhME6Nk0

###
PUT https://localhost:5000/todos/edit-todo/65cf6bb872d924ed96af6903
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDgwOTg0NzQsImV4cCI6MTcwODA5OTM3NH0.Ee9npP1c7p11u7TkYk1Y9ZIHfUjWuHyxenhuXRcFONw

{
  "title": "Todo edited"
}

###
GET https://localhost:5000/todos/get-todo/65cf65f5bdfa57ceaa151c4b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDgwOTg4NzYsImV4cCI6MTcwODA5OTc3Nn0.HVXBSvf4pPJLJycx76Y599C8kMjISxEhSJxPCIeYtBQ
