// USERS ENPOINTS requires AUTH

GET http://localhost:5000/api/csrf-token

####
GET http://localhost:5000/users

Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzAzYWQ4Y2MxZDZlMzFmYmRmNDcxZWIiLCJpYXQiOjE3Mjg1MDUyMzgsImV4cCI6MTcyODUwNjEzOH0.P9ZGwtMlqMudd5W5p_kPy0HY-37RTgSGWFkw3I_b_Ms


###
POST http://localhost:5000/users/login
Content-Type: application/json
X-CSRF-Token: S70lCEEW-SBXXiiWYRitQ5eW693JVOfX4mG4

{
  "email": "r.jamrisko@gmail.com",
  "password": "123456"
}



# http://localhost:5000/users
###

GET https://trello-clone-latest.onrender.com/api/csrf-token

####
GET https://trello-clone-latest.onrender.com/users

Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzAzYWQ4Y2MxZDZlMzFmYmRmNDcxZWIiLCJpYXQiOjE3Mjg1NTIyNDcsImV4cCI6MTcyODU1MzE0N30.MjjVizpyM6BOY1pvip2sv6nLitqqWTdIeCn0oTh6ZQY


###
POST https://trello-clone-latest.onrender.com/users/login
Content-Type: application/json
X-CSRF-Token: 8zZtabbs-baNNGkhyZqMJerDEFik7bE7X-YE


{
  "email": "r.jamrisko@gmail.com",
  "password": "123456"
}

###
DELETE https://trello-clone-latest.onrender.com/users/delete-user/65c8e5526d6a7f9d48787034
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmZiZjE2MjlkYTZlNzg1OTE1MGJjZWIiLCJpYXQiOjE3Mjc3ODc1MzgsImV4cCI6MTcyNzc4ODQzOH0.Or2zcCmhIyFCXXVAENEDanCWBsF4Nov23C44a7u5vLE

###
PUT https://trello-clone-latest.onrender.com/users/edit-user/65c8e5526d6a7f9d48787034
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM4ZTU1MjZkNmE3ZjlkNDg3ODcwMzQiLCJpYXQiOjE3MDc2ODQwMDMsImV4cCI6MTcwNzY4NDkwM30.YlNPdB__YHOPihz13ybSMWHR156ip6Uymr9ay8igRqU

{
  "firstName": "Romeo",
  "lastName": "Dzem",
  "email": "r.jamrisko@gmail.com"
}


###
POST  https://trello-clone-latest.onrender.com/users/assign-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzAzYWQ4Y2MxZDZlMzFmYmRmNDcxZWIiLCJpYXQiOjE3Mjg0ODkxMDksImV4cCI6MTcyODQ5MDAwOX0._APRhneXZSxWcZzLl52eXUSe8yg_YcrL2NFSHwx15UU


{
  "userId": "6703ad8cc1d6e31fbdf471eb",
  "role": "admin"
}


###
POST https://trello-clone-latest.onrender.com/users/register
Content-Type: application/json

{
  "firstName":"Romanko",
  "lastName": "Jamri",
  "email": "jamrisko@gmail.com",
  "password": "123456"
}
 
### 
POST https://trello-clone-latest.onrender.com/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWMxZjkwNjk1ZDc4YmVkNGJiZjE4NTciLCJpYXQiOjE3MDcyMTEyMTQsImV4cCI6MTcwNzIxMjExNH0.4TGTmZjjjhhBt2M-7O2HpKZW52SZZ8pJc5oX4dY89Yo

###
GET http://localhost:5000/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzAzYWQ4Y2MxZDZlMzFmYmRmNDcxZWIiLCJpYXQiOjE3Mjg1MDI3NTQsImV4cCI6MTcyODUwMzY1NH0.c3lAaomUxNO0ZnRkC0uZkxM3UIxiOjzSScJCwfAWJfc

###
POST https//localhost:5000/users/reset-password-request
Content-Type: application/json

{
  "email": "r.jamrisko@gmail.com"
}

###
POST https://localhost:5000/users/reset-password/65c1f90695d78bed4bbf1857/79a4a9e87c935cd1eb0609faaf21763997ebbb65e58fbf2582c281fb9c2f0454
Content-Type: application/json

{
  "password": "12345644"
}